# 是否允许私聊使用
allowPM: true
# pixiv图片直连，国内需配合代理使用
pixivDirectConnection: false
# pixiv图片反代，开启直连后反代服务则无效
pixivImageProxy: i.pixiv.re
# 每名用户每日次数限制（0 则无限制）
limit: 30

# 使用的hibiapi地址 https://github.com/mixmoe/HibiAPI
# 默认：https://hibi.Yunzai-Bot.com
# 备1：https://dengfenglai-hibiapi.hf.space
# 备2：https://hibiapi.dengfenglai.workers.dev
hibiAPI: https://hibi.Yunzai-Bot.com

# Pixiv 登录凭证刷新令牌 (Refresh Token)
# 获取方法请参考: https://github.com/mixmoe/HibiAPI/issues/53
refresh_token:

language: zh-cn # 返回语言, 会影响标签的翻译

# 发送图片质量, 可选值: large, medium, square_medium, original
sendImgQuality: original
